services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
      # POSTGRES_DB: stock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  stock-price-service:
    image: ghcr.io/astral-sh/uv:python3.12-alpine
    volumes:
      - ./stock-price-service:/app
    working_dir: /app
    command: sh -c "uv sync && uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8004:8000"
    depends_on:
      - postgres
      - localstack

  stock-price-worker:
    image: ghcr.io/astral-sh/uv:python3.12-alpine
    volumes:
      - ./stock-price-service:/app
    working_dir: /app
    command: sh -c "uv sync && uv run python worker.py"
    depends_on:
      localstack: # No dash here
        condition: service_healthy

  stock-news-service:
    image: ghcr.io/astral-sh/uv:python3.12-alpine
    volumes:
      - ./stock-news-service:/app
    working_dir: /app
    command: sh -c "uv sync && uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8003:8000"
    depends_on:
      - postgres
      - localstack

  stock-watchlist-service:
    image: ghcr.io/astral-sh/uv:python3.12-alpine
    volumes:
      - ./stock-watchlist-service:/app
    working_dir: /app
    command: sh -c "uv sync && uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8002:8000"
    depends_on:
      - postgres
      - localstack

  # stock-price-service:
  #   build: ./stock-price-service
  #   ports:
  #     - "8004:8000"
  #   env_file: ./stock-price-service/.env
  #   depends_on:
  #     - postgres

  # stock-news-service:
  #   build: ./stock-news-service
  #   ports:
  #     - "8003:8000"
  #   env_file: ./stock-news-service/.env
  #   depends_on:
  #     - postgres

  # stock-watchlist-service:
  #   build: ./stock-watchlist-service
  #   ports:
  #     - "8002:8000"
  #   env_file: ./stock-watchlist-service/.env
  #   depends_on:
  #     - postgres

  stock-ta-service:
    image: ghcr.io/astral-sh/uv:python3.12-alpine
    volumes:
      - ./stock-ta-service:/app
    working_dir: /app
    command: sh -c "uv sync && uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8005:8000"
    depends_on:
      - postgres
      - localstack

  stock-ta-worker:
    image: ghcr.io/astral-sh/uv:python3.12-alpine
    volumes:
      - ./stock-ta-service:/app
    working_dir: /app
    command: sh -c "uv sync && uv run python worker.py"
    depends_on:
      localstack:
        condition: service_healthy

  dashboard:
    # build: ./dashboard
    image: "node:25-alpine3.22"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./dashboard:/home/node/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      PRICE_API_BASE_URL: http://stock-price-service:8000
      NEWS_API_BASE_URL: http://stock-news-service:8000
      WATCHLIST_API_BASE_URL: http://stock-watchlist-service:8000
    depends_on:
      - stock-price-service
      - stock-news-service
      - stock-watchlist-service

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    env_file: ./localstack/.env
    environment:
      SERVICES: sns,sqs,s3
      DEFAULT_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      # LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d
    healthcheck:
      test: curl -fs http://localhost:4566/_localstack/init/ready | grep -q '"completed":\s*true'
      interval: 10s
      timeout: 5s
      retries: 5

  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus

volumes:
  postgres_data:
  prometheus_data:
